ALTER TABLE collector_health
    ADD COLUMN IF NOT EXISTS messages_received BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS normalized_events BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS raw_inserted BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS canonical_inserted BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS last_latency_ms BIGINT,
    ADD COLUMN IF NOT EXISTS max_latency_ms BIGINT NOT NULL DEFAULT 0;
